/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leveleditor;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

/**
 *
 * @author franz
 */
public class ThumbnailView extends javax.swing.JPanel {
    BufferedImage img;
    
    /**
     * Creates new form ThumbnailView
     */
    public ThumbnailView(BufferedImage image) {
        initComponents();
        img = image;
    }

    public BufferedImage getImg() {
        return img;
    }

    public void setImg(BufferedImage img) {
        this.img = img;
    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        ((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON);
        int x = g2d.getClipBounds().x;
        int y = g2d.getClipBounds().y;
        float width = g2d.getClipBounds().width;
        float height = g2d.getClipBounds().height;
        
        float imgwidth = img.getWidth();
        float imgheight = img.getHeight();
        
        float ratio = imgheight / imgwidth;
        float zoom;
        if (ratio > 1) {
            zoom = height / imgheight;
        } else {
            zoom = width / imgwidth;
        }
        g2d.drawImage(img, (int) x, (int) y,
                (int) (imgwidth * zoom), (int) (imgheight * zoom), this);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(200, 200));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onPressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onPressed
        
    }//GEN-LAST:event_onPressed

    private void onClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClicked
        
    }//GEN-LAST:event_onClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
